utils::globalVariables(c("Fold Change",
                         "P.Value",
                         "PValue",
                         "Score(d)",
                         "log2FoldChange",
                         "logFC",
                         "observeEvent",
                         "prob",
                         "pvalue",
                         "q-value(%)",
                         "reactiveValues",
                         "req",
                         "sessionShiny",
                         "progressShiny"))
