#' listDeByTool: makes a data.frame with genes (lines) and all executed DE tool.
#' Each tool that identify gene as DE, are marked by 1.
#'
#' @param consexpressionList A list generated by consexpressionR function
#' @param geneNames name of all genes in experiment (list)
#' @param deList List with names of all genes analysed in experiment
#'
#' @return data.frame with genes (lines) and DE tools (column), where 1 shows a
#' DE indication by tool.
#' @export
#'
#' @examples
#' data(gse95077)
#' treats = c("BM", "JJ")
#' cons_result <- runExpression(numberReplics = 3, groupName = treats,
#'                               rDataFrameCount = gse95077,
#'                               sepCharacter = ",",
#'                               experimentName = "test_cons",
#'                               outDirPath = "." )
#' expDef_result <- expressionDefinition(resultTool = cons_result, groups = treats)
#' deByTool <- listDeByTool(consexpressionList = cons_result,
#'                          geneNames = row.names(gse95077),
#'                          deList = expDef_result)
listDeByTool <- function(consexpressionList,
                         geneNames,
                         deList){
  deTool <- data.frame(matrix(0,
                              ncol = length(consexpressionList),
                              nrow = length(geneNames)))
  colnames(deTool) <- names(consexpressionList)
  row.names(deTool) <- geneNames
  toolNames <- names(consexpressionList)
  t <- 1
  for (toolDe in consexpressionList) {
    genesDe <- rownames(toolDe)
    for (i in 1:length(geneNames)) {
      if(geneNames[i] %in% row.names(deList[[t]])){
        deTool[geneNames[i], t] <- 1
      }
    }
    t <- t + 1
  }
  return(deTool)
}
