#' Bayseq execution pre-definition
#'
#' @param countMatrix table with mapped count
#' @param groupName string vector with names of treatment groups
#' @param numberReplics number of replics for each treatment
#' @param sampleSize length of sample to calculate probabilities
#' @param estimationMethod Defaults to "QL", indicating quasi-likelihood
#' estimation of priors. Currently, the only other possibilities are "ML", a
#' maximum-likelihood method, and "edgeR", the moderated dispersion estimates
#' produced by the 'edgeR' package.
#' @param clusters The number of nodes to be forked, if use parallel package
#' @param equalDispersion Should we assume equal dispersions of data across all
#'  groups in the 'cD' object? Defaults to TRUE;
#' @param priorProbabilities value used by parameter ps by bayseq::getLikelihoods function
#' @param reestimationType value used by parameter pET by bayseq::getLikelihoods function
#' @param topCountGroup value used by parameter group by bayseq::topCounts function
#' @param numberTopCount value used by parameter number by bayseq::topCounts function
#'
#' @return extracted results from baySeq (generated by bayseq::topCounts function)
#' @export
#'
#' @examples
runBaySeq <- function  (countMatrix,
                        groupName,
                        numberReplics,
                        sampleSize = 1000,
                        estimationMethod = "QL",
                        clusters=2,
                        equalDispersion = TRUE,
                        priorProbabilities=c(0.5, 0.5), #0.5 por grupo??
                        reestimationType = "BIC",
                        topCountGroup = "DE",
                        numberTopCount=65000){

    if(require("parallel")) cl <- parallel::makeCluster(clusters) else cl <- NULL
    groups <- list(NDE = factor(rep(as.character(groupName[1]), each = numberReplics*length(groupName))),
                   DE = factor(rep(groupName, each=numberReplics)))
    CD <- new("countData",
              data = countMatrix,
              replicates = rep(groupName, each=numberReplics),
              groups = groups)
    baySeq::libsizes(CD) <- baySeq::getLibsizes(CD)
    CD <- baySeq::getPriors.NB(CD,
                               samplesize = sampleSize,
                               cl = cl)
    CD <- baySeq::getLikelihoods(CD,
                                 bootStraps = 3,
                                 cl=cl)
    result <- baySeq::topCounts(CD,
                       group = topCountGroup,
                        number = numberTopCount,
                        normaliseData = TRUE)
    if(!is.null(cl)) stopCluster(cl)
    return (result)
}
