#' Execute DESeq2 DGE default analysis
#' is configured to read only kallisto files, and count data
#'
#' @param countMatrix original table count or abundance data
#' @param designExperiment replicate and treatment by samples
#' @param pathDirsRuns parent directory that contains one folder with all kallisto output
#' @param pathReportFile file path with report by sample, conditions and runs
#' @param subDirRuns sub dir by pathRepRuns
#' @param fileKallisto file output kallisto, exemaple: "abundance.tsv" or "quant.sf.gz"
#'
#' @return extracted results from DESeq2 (generated by DESeq2::results function)
#' @export
#' @import DESeq2
#'
#' @examples   # DESeq2::resultsNames(dds)
# res <- DESeq2::results(dds, name="condition_vs_consition")
#
runDeseq2 <- function(countMatrix,
                      groupName,
                      numberReplics,
                     designExperiment,
                     pairedEnd = "single-read",
                     pathDirRuns = ".",
                     pathReportFile = "report_txi.txt",
                     subDirRuns = "dir_runs",
                     fileKallisto = "abundance.tsv"){
  colDat <- NULL
  colDat$condiction <- as.factor(rep(groupName, each=numberReplics))
  colDat$type <- factor(rep("single-read", (numberReplics* length(groupName))))
  colDat <- as.data.frame(colDat, row.names = colnames(countMatrix))

  dds<-DESeqDataSetFromMatrix(countMatrix,
                              colData = colDat,
                              design = ~condiction)
  if(typeof(countMatrix) == "double"){
    print("Dataset isn't COUNT data")
    # DESeq2 kallisto
    dds <- abundanceKallistoImport (pathReportRuns = pathDirRuns,
                                    pathReportFile = pathReportFile,
                                    dirRuns = subDirRuns,
                                    fileKallistoAbundance = fileKallisto,
                                    conditionList = designExperiment)
    dds$condition <- factor(dds$condition, levels = groupName)
  }else{ # testar count data
    print("Dataset is COUNT data")
    colDat <- NULL
    colDat$condiction <- as.factor(rep(groupName, each=numberReplics))
    colDat$type <- factor(rep("single-read", (numberReplics* length(groupName))))
    colDat <- as.data.frame(colDat, row.names = colnames(countMatrix))
    dds<-DESeqDataSetFromMatrix(countMatrix,
                                colData = colDat,
                                design = ~condiction)
  }
  dds <- DESeq2::DESeq(dds)
  res <- DESeq2::results(dds)
  return(res)
}
