#' Execute DESeq2 DGE default analysis
#' is configured to read only kallisto files, and count data
#'
#' @param countMatrix original table count or abundance data
#' @param numberReplics number of replicate (technical or biological) by sample
#' @param groupName text, name of samples or treatment
#' @param designExperiment replic and treatment by samples
#' @param fitTypeParam either "parametric", "local", "mean", or "glmGamPoi" for the type of fitting of dispersions to the mean intensity
#' @param controlGroup specific reference level
#' @return extracted results from DESeq2 (generated by DESeq2::results function)
#' @export
#' @import DESeq2
#'
#' @examples
#' groupNameModel = c("BM","JJ")
#' numberReplicsModel = 3
#' toolResult <- NULL
#' toolResult$deseq2 <- runDeseq2(countMatrix = gse95077,
#'                                groupName = groupNameModel,
#'                                numberReplics = numberReplicsModel,
#'                                fitTypeParam = "local")
runDeseq2 <- function(countMatrix,
                      groupName,
                      numberReplics,
                      designExperiment,
                      controlGroup = "",
                      fitTypeParam = "local"){
  colDat <- NULL
  colDat$condiction <- as.factor(rep(groupName, each=numberReplics))
  colDat$type <- as.factor(rep(groupName, each=numberReplics))
  colDat <- as.data.frame(colDat, row.names = colnames(countMatrix))
  dds<-DESeqDataSetFromMatrix(countMatrix,
                              colData = colDat,
                              design = ~condiction)
  if(controlGroup == ""){
    dds$condition <- factor(dds$condiction, levels = groupName)
  }else{
    dds$condition <- relevel(dds$condiction, ref = controlGroup)
  }
  if(typeof(countMatrix) == "double"){
    cat("DESeq2 canceled. Dataset isn't COUNT data")
  }else{
    print("Dataset is COUNT data")
    dds <- DESeq2::DESeq(dds, fitType = fitTypeParam)
    res <- DESeq2::results(dds, contrast = c("condiction",groupName))
    resOrdered <- res[order(res$pvalue),]
    dfDeseq2 <- as.data.frame(resOrdered)
    return(dfDeseq2)
  }
  return(NULL)
}
