#' Execute knowSeq differential Expression analyse
#'
#' @param countMatrix original table count or abundance data
#' @param groupName replicate and treatment by samples
#' @param numberReplic number of replicate (technical or biological) by sample
#' @param filterId The attribute used as filter to return the rest of the attributes.
#' @param notSapiens A boolean value that indicates if the user wants the human annotation or another annotation available in BiomaRt. The possible not human dataset can be consulted by calling the following function: biomaRt::listDatasets(useMart("ensembl")).
#' @return extracted results from KnowSeq (generated by KnowSeq::DEGsExtraction() function)
#' @export
#'
#' @examples
#' \dontrun{
#' library(cqn)
#' groupNameModel = c("BM","JJ")
#' numberReplicsModel = 3
#' toolResult <- NULL
#' toolResult$knowSeq <- runKnowSeq(countMatrix = gse95077,
#'                                groupName = groupNameModel,
#'                                numberReplic = numberReplicsModel)
#'                                }
runKnowSeq <- function(countMatrix,
                       groupName,
                       numberReplic,
                       filterId="ensembl_gene_id",
                       notSapiens = FALSE){
  if(length(groupName) > 2){
    return(NULL)
  }else{
    designExperiment <- rep(groupName, each = numberReplic)
    geneNames = as.character(row.names(countMatrix))

    myAnnotation <- KnowSeq::getGenesAnnotation(values = geneNames,
                                                filter=filterId,
                                                notHSapiens = notSapiens)
    designExperiment <- rep(groupName, each=numberReplic)
    expressionMatrix <- KnowSeq::calculateGeneExpressionValues(countsMatrix = countMatrix,
                                                               annotation = myAnnotation,
                                                               genesNames = FALSE)
    knowSeq <- KnowSeq::DEGsExtraction(expressionMatrix,
                                       labels = designExperiment,
                                       multiDegsMethod = "cov")
    return(knowSeq$DEG_Results$DEGs_Table)
  }
}
