#' Execute knowSeq differential Expression analyse
#'
#' @param count original table count or abundance data
#' @param groupName replicate and treatment by samples
#' @param numberReplic number of replicate (technical or biological) by sample
#' @param filterId The attribute used as filter to return the rest of the attributes.
#' @param notSapiens A boolean value that indicates if the user wants the human annotation or another annotation available in BiomaRt. The possible not human dataset can be consulted by calling the following function: biomaRt::listDatasets(useMart("ensembl")).
#' @return extracted results from KnowSeq (generated by KnowSeq::DEGsExtraction() function)
#' @export
#'
#' @examples
#' \dontrun{
#' data(gse95077)
#' treats = c("BM", "JJ")
#' toolResult <- NULL
#' toolResult$knowSeq <- runKnowSeq(count = gse95077,
#'                                groupName = treats,
#'                                numberReplic = 3)
#'  }
runKnowSeq <- function(count,
                       groupName,
                       numberReplic,
                       filterId="ensembl_gene_id",
                       notSapiens = FALSE){
  if(length(groupName) > 2){
    return(NULL)
  }else{
    designExperiment <- rep(groupName, each = numberReplic)
    geneNames = as.character(row.names(count))

    myAnnotation <- KnowSeq::getGenesAnnotation(values = geneNames,
                                                filter=filterId,
                                                notHSapiens = notSapiens)
    designExperiment <- rep(groupName, each=numberReplic)
    m <- as.matrix(count)
    expressionMatrix <- KnowSeq::calculateGeneExpressionValues(countsMatrix = m,
                                                               annotation = myAnnotation,
                                                               genesNames = FALSE)
    knowSeq <- KnowSeq::DEGsExtraction(expressionMatrix,
                                       labels = designExperiment,
                                       multiDegsMethod = "cov",
                                       lfc = -20)
    return(knowSeq$DEG_Results$DEGs_Table)
  }
}
